"""Meta-Rule SQLite persistence — DB I/O for meta_rules / super_meta_rules. Core logic plus
:class:`SuperMetaRule` discovery in ``meta_rules.py``. DP scaffold (:class:`DPConfig`) off."""

from __future__ import annotations

import contextlib
import json
import random
import sqlite3
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

from .._types import RuleTransferScope
from .meta_rules import TIER_SUPER_META, MetaRule, SuperMetaRule

if TYPE_CHECKING:
    from pathlib import Path

# ---------------------------------------------------------------------------
# Meta-Rule DDL
# ---------------------------------------------------------------------------

_CREATE_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS meta_rules (
    id TEXT PRIMARY KEY,
    principle TEXT NOT NULL,
    source_categories TEXT,
    source_lesson_ids TEXT,
    confidence REAL,
    created_session INTEGER,
    last_validated_session INTEGER,
    scope TEXT,
    examples TEXT,
    context_weights TEXT
);
"""

_ADD_CONTEXT_WEIGHTS_SQL = "ALTER TABLE meta_rules ADD COLUMN context_weights TEXT"

_ADD_APPLIES_WHEN_SQL = "ALTER TABLE meta_rules ADD COLUMN applies_when TEXT"

_ADD_NEVER_WHEN_SQL = "ALTER TABLE meta_rules ADD COLUMN never_when TEXT"

_ADD_TRANSFER_SCOPE_SQL = "ALTER TABLE meta_rules ADD COLUMN transfer_scope TEXT DEFAULT 'personal'"

# Provenance of the principle text (deterministic / llm_synth / human_curated).
# Default is 'deterministic' for safety — pre-existing rows from before this
# migration are auto-generated by the clusterer and should NOT be injected
# (2026-04-14 ablation showed they regress correctness).
_ADD_SOURCE_SQL = "ALTER TABLE meta_rules ADD COLUMN source TEXT DEFAULT 'deterministic'"


def ensure_table(db_path: str | Path) -> None:
    """Create the meta_rules table if it does not exist.

    Also migrates existing tables by adding new columns when they are
    missing (backward-compatible upgrade).

    Args:
        db_path: Path to the SQLite database file.
    """
    conn = sqlite3.connect(str(db_path))
    try:
        conn.execute(_CREATE_TABLE_SQL)
        # Migrate: add columns if table existed before this version
        for stmt in (
            _ADD_CONTEXT_WEIGHTS_SQL,
            _ADD_APPLIES_WHEN_SQL,
            _ADD_NEVER_WHEN_SQL,
            _ADD_TRANSFER_SCOPE_SQL,
            _ADD_SOURCE_SQL,
        ):
            with contextlib.suppress(sqlite3.OperationalError):
                conn.execute(stmt)
        conn.commit()
    finally:
        conn.close()


def save_meta_rules(db_path: str | Path, metas: list[MetaRule]) -> int:
    """Persist meta-rules to system.db, replacing all existing rows.

    Args:
        db_path: Path to the SQLite database file.
        metas: Meta-rules to save.

    Returns:
        Number of meta-rules saved.
    """
    ensure_table(db_path)
    conn = sqlite3.connect(str(db_path))
    try:
        conn.execute("BEGIN IMMEDIATE")
        conn.execute("DELETE FROM meta_rules")
        for meta in metas:
            conn.execute(
                """INSERT INTO meta_rules
                   (id, principle, source_categories, source_lesson_ids,
                    confidence, created_session, last_validated_session,
                    scope, examples, context_weights, applies_when, never_when,
                    transfer_scope, source)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                (
                    meta.id,
                    meta.principle,
                    json.dumps(meta.source_categories),
                    json.dumps(meta.source_lesson_ids),
                    meta.confidence,
                    meta.created_session,
                    meta.last_validated_session,
                    json.dumps(meta.scope),
                    json.dumps(meta.examples),
                    json.dumps(meta.context_weights),
                    json.dumps(meta.applies_when),
                    json.dumps(meta.never_when),
                    meta.transfer_scope.value,
                    meta.source,
                ),
            )
        conn.commit()
        return len(metas)
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def load_meta_rules(db_path: str | Path) -> list[MetaRule]:
    """Load meta-rules from system.db.

    Args:
        db_path: Path to the SQLite database file.

    Returns:
        List of :class:`MetaRule` objects, sorted by confidence
        descending.  Empty list if the table does not exist.
    """
    conn = sqlite3.connect(str(db_path))
    try:
        # Check if table exists
        cursor = conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name='meta_rules'"
        )
        if not cursor.fetchone():
            return []

        # Legacy brains may predate the `source` column. Probe the schema and
        # synthesize `'deterministic'` in the SELECT when the column is absent
        # so read-only callers (e.g. inject_brain_rules) don't have to trigger
        # a write migration. Keeps the query shape stable for row unpacking.
        existing_cols = {r[1] for r in conn.execute("PRAGMA table_info(meta_rules)")}
        source_expr = "source" if "source" in existing_cols else "'deterministic' AS source"

        rows = conn.execute(
            f"""SELECT id, principle, source_categories, source_lesson_ids,
                      confidence, created_session, last_validated_session,
                      scope, examples, context_weights, applies_when, never_when,
                      transfer_scope, {source_expr}
               FROM meta_rules
               ORDER BY confidence DESC"""
        ).fetchall()

        # Map stored strings back to enum values
        _SCOPE_MAP = {s.value: s for s in RuleTransferScope}

        metas: list[MetaRule] = []
        for row in rows:
            metas.append(
                MetaRule(
                    id=row[0],
                    principle=row[1],
                    source_categories=json.loads(row[2]) if row[2] else [],
                    source_lesson_ids=json.loads(row[3]) if row[3] else [],
                    confidence=row[4] or 0.0,
                    created_session=row[5] or 0,
                    last_validated_session=row[6] or 0,
                    scope=json.loads(row[7]) if row[7] else {},
                    examples=json.loads(row[8]) if row[8] else [],
                    context_weights=json.loads(row[9]) if row[9] else {"default": 1.0},
                    applies_when=json.loads(row[10]) if row[10] else [],
                    never_when=json.loads(row[11]) if row[11] else [],
                    transfer_scope=_SCOPE_MAP.get(row[12], RuleTransferScope.PERSONAL)
                    if row[12]
                    else RuleTransferScope.PERSONAL,
                    source=row[13] or "deterministic",
                )
            )
        return metas
    finally:
        conn.close()


# ---------------------------------------------------------------------------
# Super-Meta-Rule DDL
# ---------------------------------------------------------------------------

_CREATE_SUPER_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS super_meta_rules (
    id TEXT PRIMARY KEY,
    abstraction TEXT NOT NULL,
    source_meta_rule_ids TEXT,
    tier INTEGER,
    confidence REAL,
    context_weights TEXT,
    source_categories TEXT,
    created_session INTEGER,
    last_validated_session INTEGER,
    scope TEXT,
    examples TEXT
);
"""

_ADD_SUPER_APPLIES_WHEN_SQL = "ALTER TABLE super_meta_rules ADD COLUMN applies_when TEXT"

_ADD_SUPER_NEVER_WHEN_SQL = "ALTER TABLE super_meta_rules ADD COLUMN never_when TEXT"

_ADD_SUPER_TRANSFER_SCOPE_SQL = (
    "ALTER TABLE super_meta_rules ADD COLUMN transfer_scope TEXT DEFAULT 'personal'"
)


def ensure_super_table(db_path: str | Path) -> None:
    """Create the super_meta_rules table if it does not exist.

    Also migrates existing tables by adding ``applies_when`` and
    ``never_when`` columns when missing (backward-compatible upgrade).

    Args:
        db_path: Path to the SQLite database file.
    """
    conn = sqlite3.connect(str(db_path))
    try:
        conn.execute(_CREATE_SUPER_TABLE_SQL)
        for stmt in (
            _ADD_SUPER_APPLIES_WHEN_SQL,
            _ADD_SUPER_NEVER_WHEN_SQL,
            _ADD_SUPER_TRANSFER_SCOPE_SQL,
        ):
            with contextlib.suppress(sqlite3.OperationalError):
                conn.execute(stmt)
        conn.commit()
    finally:
        conn.close()


def save_super_meta_rules(db_path: str | Path, supers: list[SuperMetaRule]) -> int:
    """Persist super-meta-rules to system.db, replacing all existing rows.

    Args:
        db_path: Path to the SQLite database file.
        supers: Super-meta-rules to save (tier 2 and 3).

    Returns:
        Number of super-meta-rules saved.
    """
    ensure_super_table(db_path)
    conn = sqlite3.connect(str(db_path))
    try:
        conn.execute("BEGIN IMMEDIATE")
        conn.execute("DELETE FROM super_meta_rules")
        for s in supers:
            conn.execute(
                """INSERT INTO super_meta_rules
                   (id, abstraction, source_meta_rule_ids, tier,
                    confidence, context_weights, source_categories,
                    created_session, last_validated_session, scope, examples,
                    applies_when, never_when, transfer_scope)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                (
                    s.id,
                    s.abstraction,
                    json.dumps(s.source_meta_rule_ids),
                    s.tier,
                    s.confidence,
                    json.dumps(s.context_weights),
                    json.dumps(s.source_categories),
                    s.created_session,
                    s.last_validated_session,
                    json.dumps(s.scope),
                    json.dumps(s.examples),
                    json.dumps(s.applies_when),
                    json.dumps(s.never_when),
                    s.transfer_scope.value,
                ),
            )
        conn.commit()
        return len(supers)
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def load_super_meta_rules(db_path: str | Path) -> list[SuperMetaRule]:
    """Load super-meta-rules from system.db.

    Args:
        db_path: Path to the SQLite database file.

    Returns:
        List of :class:`SuperMetaRule` objects, sorted by tier descending
        then confidence descending.  Empty list if table does not exist.
    """
    conn = sqlite3.connect(str(db_path))
    try:
        cursor = conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name='super_meta_rules'"
        )
        if not cursor.fetchone():
            return []

        rows = conn.execute(
            """SELECT id, abstraction, source_meta_rule_ids, tier,
                      confidence, context_weights, source_categories,
                      created_session, last_validated_session, scope, examples,
                      applies_when, never_when, transfer_scope
               FROM super_meta_rules
               ORDER BY tier DESC, confidence DESC"""
        ).fetchall()

        _SCOPE_MAP = {s.value: s for s in RuleTransferScope}

        supers: list[SuperMetaRule] = []
        for row in rows:
            supers.append(
                SuperMetaRule(
                    id=row[0],
                    abstraction=row[1],
                    source_meta_rule_ids=json.loads(row[2]) if row[2] else [],
                    tier=row[3] or TIER_SUPER_META,
                    confidence=row[4] or 0.0,
                    context_weights=json.loads(row[5]) if row[5] else {"default": 1.0},
                    source_categories=json.loads(row[6]) if row[6] else [],
                    created_session=row[7] or 0,
                    last_validated_session=row[8] or 0,
                    scope=json.loads(row[9]) if row[9] else {},
                    examples=json.loads(row[10]) if row[10] else [],
                    applies_when=json.loads(row[11]) if row[11] else [],
                    never_when=json.loads(row[12]) if row[12] else [],
                    transfer_scope=_SCOPE_MAP.get(row[13], RuleTransferScope.PERSONAL)
                    if row[13]
                    else RuleTransferScope.PERSONAL,
                )
            )
        return supers
    finally:
        conn.close()


# ---------------------------------------------------------------------------
# Correction Pattern Tracking (cross-session)
# ---------------------------------------------------------------------------

# Severity weights for pattern graduation scoring (different scale from
# self_improvement.SEVERITY_WEIGHTS which is for confidence-delta math)
PATTERN_SEVERITY_WEIGHTS = {
    "major": 2.0,
    "rewrite": 2.5,
    "moderate": 1.5,
    "minor": 1.0,
    "trivial": 0.5,
}


def ensure_pattern_table(db_path: str | Path) -> None:
    """Create correction_patterns table if it doesn't exist."""
    conn = sqlite3.connect(str(db_path))
    try:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS correction_patterns (
                pattern_hash TEXT NOT NULL,
                category TEXT NOT NULL,
                representative_text TEXT NOT NULL,
                session_id INTEGER NOT NULL,
                severity TEXT DEFAULT 'minor',
                severity_weight REAL DEFAULT 1.0,
                created_at TEXT DEFAULT (datetime('now')),
                UNIQUE(pattern_hash, session_id)
            )
        """)
        conn.execute("""
            CREATE INDEX IF NOT EXISTS idx_patterns_hash
            ON correction_patterns(pattern_hash)
        """)
        conn.commit()
    finally:
        conn.close()


def upsert_correction_pattern(
    db_path: str | Path,
    pattern_hash: str,
    category: str,
    representative_text: str,
    session_id: int,
    severity: str = "minor",
) -> None:
    """Record a correction pattern occurrence for a session."""
    ensure_pattern_table(db_path)
    weight = PATTERN_SEVERITY_WEIGHTS.get(severity, 1.0)
    conn = sqlite3.connect(str(db_path))
    try:
        conn.execute(
            """INSERT INTO correction_patterns
               (pattern_hash, category, representative_text, session_id, severity, severity_weight)
               VALUES (?, ?, ?, ?, ?, ?)
               ON CONFLICT(pattern_hash, session_id) DO UPDATE SET
                 severity = CASE WHEN excluded.severity_weight > severity_weight
                                THEN excluded.severity ELSE severity END,
                 severity_weight = MAX(severity_weight, excluded.severity_weight),
                 representative_text = excluded.representative_text
            """,
            (pattern_hash, category, representative_text, session_id, severity, weight),
        )
        conn.commit()
    finally:
        conn.close()


def upsert_correction_patterns_batch(
    db_path: str | Path,
    patterns: list[tuple[str, str, str, int, str]],
) -> int:
    """Batch upsert multiple correction patterns in one connection.

    Each tuple: (pattern_hash, category, representative_text, session_id, severity).
    Returns number of rows upserted.
    """
    if not patterns:
        return 0
    ensure_pattern_table(db_path)
    conn = sqlite3.connect(str(db_path))
    try:
        rows = []
        for pattern_hash, category, representative_text, session_id, severity in patterns:
            weight = PATTERN_SEVERITY_WEIGHTS.get(severity, 1.0)
            rows.append((pattern_hash, category, representative_text, session_id, severity, weight))
        conn.executemany(
            """INSERT INTO correction_patterns
               (pattern_hash, category, representative_text, session_id, severity, severity_weight)
               VALUES (?, ?, ?, ?, ?, ?)
               ON CONFLICT(pattern_hash, session_id) DO UPDATE SET
                 severity = CASE WHEN excluded.severity_weight > severity_weight
                                THEN excluded.severity ELSE severity END,
                 severity_weight = MAX(severity_weight, excluded.severity_weight),
                 representative_text = excluded.representative_text
            """,
            rows,
        )
        conn.commit()
        return len(rows)
    finally:
        conn.close()


# ---------------------------------------------------------------------------
# Differential-Privacy Export Scaffold (off by default)
# ---------------------------------------------------------------------------
#
# Meta-rules are compressed behavioral fingerprints by construction: they
# encode *what a specific operator consistently corrects*.  If marketplace
# consumers can query meta-rules across brains without perturbation, a
# Carlini-style membership-inference attack (Carlini et al. 2021; see also
# Dwork & Roth 2014 §1.1 "reconstruction attacks") becomes trivial — a
# sufficiently motivated consumer learns, at minimum, which correction
# categories a brain's operator cares about, and at worst, recovers
# verbatim principle text that may contain private context.
#
# Today ε = ∞ (no noise, no DP, raw aggregation).  This scaffold lets
# marketplace (Phase 4) flip on Laplace-mechanism perturbation via a
# single config toggle.  It is deliberately *off-by-default* — no current
# API path is affected unless DPConfig.enabled is explicitly True.
#
# COMPOSITION WARNING (adversary check):
#   Basic sequential composition (Dwork & Roth 2014 Theorem 3.16): K
#   ε-DP queries compose to Kε.  With ε=1.0 and a marketplace consumer
#   querying 100 meta-rules from the same brain, the effective ε is
#   **100.0** — i.e. essentially no privacy.  Defenses require one of:
#     (a) a per-brain ε-budget tracker that blocks queries once spent,
#     (b) approximate (ε, δ)-DP with advanced composition
#         (Theorem 3.20: ε' ≈ √(2K·ln(1/δ'))·ε),
#     (c) RDP / moments-accountant per Abadi et al. 2016 §3, suitable for
#         Gaussian mechanism and much tighter for repeated queries.
#   This scaffold implements (a)'s audit-log hook but does NOT yet
#   enforce budgets — that's Phase 4 marketplace work.  Consumers that
#   flip DP on in production MUST add budget enforcement before
#   exposing the endpoint to untrusted clients.


@dataclass
class DPConfig:
    """Configuration for differential-privacy noise on meta-rule exports.

    Off by default.  Flip ``enabled=True`` to apply the Laplace mechanism
    (Dwork et al. 2006) to numerical fields and suppress raw text fields
    on the cloud export path.

    Attributes:
        enabled: Master switch.  When False, :func:`apply_dp_to_export_row`
            is a no-op — rows pass through unchanged.  Default: ``False``.
        epsilon: Privacy budget *per query*.  Smaller = more noise = more
            privacy.  Default ``1.0``.  Note that composition across K
            queries yields Kε under basic composition — see module-level
            COMPOSITION WARNING above.
        mechanism: Noise mechanism identifier.  Currently only
            ``"laplace"`` is implemented; ``"gaussian"`` is reserved for
            RDP accounting (Abadi et al. 2016) when marketplace ships.
        clip_norm: Per-field L1 clipping bound applied *before* noise.
            Bounds the sensitivity of numerical fields (confidence,
            fire_count, source counts) to ``clip_norm`` so the Laplace
            scale ``sensitivity/epsilon`` is well-defined.  Default
            ``1.0`` — matches the natural [0, 1] range of ``confidence``.
    """

    enabled: bool = False
    epsilon: float = 1.0
    mechanism: str = "laplace"
    clip_norm: float = 1.0


def _laplace_noise(scale: float, rng: random.Random) -> float:
    """Draw a sample from Laplace(0, scale).

    Inverse-CDF method: if U ~ Uniform(-0.5, 0.5), then
    ``-scale * sign(U) * log(1 - 2|U|)`` is Laplace(0, scale).  Using a
    ``random.Random`` instance lets callers pass ``random.SystemRandom``
    in production; tests use a seeded PRNG for reproducibility.
    """
    import math

    u = rng.random() - 0.5
    if u == 0:
        return 0.0
    return -scale * math.copysign(1.0, u) * math.log(1.0 - 2.0 * abs(u))


def _clip(value: float, bound: float) -> float:
    """Clip a value to [-bound, bound].  Required before Laplace noise
    so the per-field sensitivity ≤ ``bound``."""
    return max(-bound, min(bound, value))


def apply_dp_to_export_row(
    row: dict[str, Any],
    config: DPConfig,
    *,
    rng: random.Random | None = None,
) -> dict[str, Any]:
    """Transform a meta-rule export row in-place for DP-safe release.

    When ``config.enabled`` is False (the default), returns ``row``
    unchanged — this function is a scaffold, not an enforcement layer.

    When enabled, applies the Laplace mechanism (Dwork et al. 2006) to
    numerical fields and strips raw text fields:

    **Numerical fields** (``confidence``, ``fire_count``, any integer
    source-count derived from ``source_lesson_ids``):
        1. Clip to ``[-clip_norm, clip_norm]`` to bound sensitivity.
        2. Add Laplace noise with scale ``clip_norm / epsilon``.
        3. ``round``/``max(0, …)`` to preserve type sanity.  This is
           post-processing (Dwork & Roth 2014 Proposition 2.1) and does
           not weaken the DP guarantee.

    **Text fields** (``principle``, ``description``, ``examples``,
    ``representative_text``): raw text is **replaced with a placeholder
    under DP**.  The Laplace mechanism is defined for numerical queries;
    releasing raw natural-language text from a behavioral fingerprint
    would leak high-entropy operator-identifying content that no
    per-query noise can meaningfully mask.  Only *structural features*
    (category, source count, tier, confidence bucket) are shared.  This
    is a deliberate scoping choice, not DP itself — marketplace clients
    should consume structural features only; text remains on-device.

    Args:
        row: A mutable dict representing one meta-rule as returned from
            the cloud DB layer.  Must be safe to modify (copy upstream
            if the caller reuses it).
        config: DP configuration.  ``config.enabled=False`` -> no-op.
        rng: Optional ``random.Random`` instance for noise draws.
            Defaults to ``random.SystemRandom()`` for non-deterministic
            draws in production.  Tests pass a seeded PRNG.

    Returns:
        The same ``row`` dict, mutated.  Returned for call-chaining.

    Raises:
        ValueError: If ``config.mechanism`` is not ``"laplace"`` (other
            mechanisms reserved for future RDP accounting).
    """
    if not config.enabled:
        return row

    if config.mechanism != "laplace":
        raise ValueError(
            f"DPConfig.mechanism={config.mechanism!r} not implemented; "
            "only 'laplace' is currently supported"
        )
    if config.epsilon <= 0:
        raise ValueError(f"DPConfig.epsilon must be > 0, got {config.epsilon}")
    if config.clip_norm <= 0:
        raise ValueError(f"DPConfig.clip_norm must be > 0, got {config.clip_norm}")

    if rng is None:
        rng = random.SystemRandom()

    scale = config.clip_norm / config.epsilon

    # --- Numerical perturbation -------------------------------------------
    if "confidence" in row and row["confidence"] is not None:
        clipped = _clip(float(row["confidence"]), config.clip_norm)
        noised = clipped + _laplace_noise(scale, rng)
        # confidence is naturally in [0, 1]; clamp post-noise for display sanity
        row["confidence"] = max(0.0, min(1.0, noised))

    if "fire_count" in row and row["fire_count"] is not None:
        clipped = _clip(float(row["fire_count"]), config.clip_norm)
        noised = clipped + _laplace_noise(scale, rng)
        # fire_count is a non-negative integer count
        row["fire_count"] = max(0, round(noised))

    # Source-count: replace list of IDs with a noised cardinality so we
    # neither leak lesson IDs nor publish an un-noised count.
    if "source_lesson_ids" in row:
        ids = row.get("source_lesson_ids") or []
        raw_count = len(ids) if isinstance(ids, list) else 0
        clipped = _clip(float(raw_count), config.clip_norm)
        noised = clipped + _laplace_noise(scale, rng)
        row["source_lesson_count"] = max(0, round(noised))
        row["source_lesson_ids"] = []  # never export raw IDs under DP

    # --- Text suppression --------------------------------------------------
    # Replace raw principle/description/examples with a structural token.
    # See docstring for rationale — Laplace doesn't cover natural language.
    for text_field in ("principle", "description", "representative_text"):
        if row.get(text_field):
            row[text_field] = "[DP-SUPPRESSED]"
    if "examples" in row:
        row["examples"] = []  # examples are verbatim correction text

    return row


def query_graduation_candidates(
    db_path: str | Path,
    min_sessions: int = 2,
    min_score: float = 3.0,
) -> list[dict]:
    """Find correction patterns ready for meta-rule graduation.

    Returns patterns where:
    - Distinct sessions >= min_sessions
    - Sum of severity weights >= min_score
    """
    ensure_pattern_table(db_path)
    conn = sqlite3.connect(str(db_path))
    try:
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            """WITH representative AS (
                 SELECT
                   pattern_hash,
                   category,
                   representative_text,
                   ROW_NUMBER() OVER (PARTITION BY pattern_hash ORDER BY created_at DESC) AS rn
                 FROM correction_patterns
               ),
               aggregates AS (
                 SELECT
                   pattern_hash,
                   COUNT(DISTINCT session_id) AS distinct_sessions,
                   SUM(severity_weight) AS weighted_score,
                   MIN(created_at) AS first_seen,
                   MAX(created_at) AS last_seen,
                   GROUP_CONCAT(DISTINCT session_id) AS session_ids
                 FROM correction_patterns
                 GROUP BY pattern_hash
                 HAVING COUNT(DISTINCT session_id) >= ?
                    AND SUM(severity_weight) >= ?
               )
               SELECT
                 r.pattern_hash,
                 r.category,
                 r.representative_text,
                 a.distinct_sessions,
                 a.weighted_score,
                 a.first_seen,
                 a.last_seen,
                 a.session_ids
               FROM representative r
               INNER JOIN aggregates a ON r.pattern_hash = a.pattern_hash
               WHERE r.rn = 1
               ORDER BY a.weighted_score DESC
            """,
            (min_sessions, min_score),
        ).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()
