"""
Reporting — Brain briefing + health reports.
=============================================
Merged from: brain_briefing.py + reports.py
Inspired by: fest.build's "fest next" (agent-agnostic context)

Generates a single markdown file that any AI agent can consume:
Claude Code (CLAUDE.md), Cursor (.cursorrules), Copilot
(.github/copilot-instructions.md), or any system prompt.

No MCP, no SDK, no Python required on the consumer side.
Just a file the agent reads.

Usage::

    from gradata.enhancements.reporting import (
        BrainBriefing, generate_briefing, export_briefing,
    )

    briefing = generate_briefing(brain)
    print(briefing.to_markdown())

    # Export to multiple formats at once
    export_briefing(brain, formats=["claude", "cursor", "copilot"])
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

__all__ = [
    "EXPORT_TARGETS",
    "BrainBriefing",
    "export_briefing",
    "generate_briefing",
]

# Where to write briefing files for each agent platform
EXPORT_TARGETS: dict[str, str] = {
    "claude": "BRAIN-RULES.md",
    "cursor": ".cursorrules",
    "copilot": ".github/copilot-instructions.md",
    "generic": "brain-briefing.md",
}


@dataclass
class BriefingRule:
    """A single rule from the brain, formatted for injection."""

    category: str
    description: str
    confidence: float
    state: str  # INSTINCT, PATTERN, RULE
    fire_count: int = 0

    @property
    def priority(self) -> str:
        if self.state == "RULE":
            return "MUST"
        elif self.state == "PATTERN":
            return "SHOULD"
        return "MAY"


@dataclass
class BrainBriefing:
    """Complete brain briefing for agent consumption.

    Attributes:
        rules: Active graduated rules.
        anti_patterns: Things to avoid.
        recent_corrections: Summary of recent corrections.
        brain_health: Health metrics.
        metadata: Additional context.
    """

    rules: list[BriefingRule] = field(default_factory=list)
    anti_patterns: list[str] = field(default_factory=list)
    recent_corrections: list[dict[str, Any]] = field(default_factory=list)
    brain_health: dict[str, Any] = field(default_factory=dict)
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_markdown(self) -> str:
        """Generate the full briefing as dense, compact markdown.

        Design: every rule = 1 line. No verbose headers, no preamble prose.
        48 rules = ~50 lines. Concise enough to avoid context bloat.
        The ETH Zurich penalty comes from verbosity, not from rule count.
        """
        lines: list[str] = []

        lines.append("# Brain Rules (auto-generated by Gradata)")

        # Rules: one line each, grouped by enforcement tier
        must_rules = [r for r in self.rules if r.priority == "MUST"]
        should_rules = [r for r in self.rules if r.priority == "SHOULD"]

        if must_rules:
            lines.append("")
            lines.append("## MUST follow (proven rules)")
            for r in must_rules:
                lines.append(f"- {r.category}: {r.description}")

        if should_rules:
            lines.append("")
            lines.append("## SHOULD follow (emerging patterns)")
            for r in should_rules:
                lines.append(f"- {r.category}: {r.description}")

        # Anti-patterns: compact list
        if self.anti_patterns:
            lines.append("")
            lines.append("## DO NOT")
            for ap in self.anti_patterns:
                lines.append(f"- {ap}")

        # Recent corrections: only if useful context
        if self.recent_corrections:
            lines.append("")
            lines.append("## Recent mistakes (avoid repeating)")
            for c in self.recent_corrections[:5]:
                cat = c.get("category", "?")
                desc = c.get("summary", "")[:80]
                if desc:
                    lines.append(f"- {cat}: {desc}")

        return "\n".join(lines)

    @property
    def rule_count(self) -> int:
        return len(self.rules)

    @property
    def has_content(self) -> bool:
        return bool(self.rules or self.anti_patterns or self.recent_corrections)


def generate_briefing(
    brain: Any,
    max_rules: int = 0,
    min_confidence: float = 0.60,
    include_instincts: bool = False,
) -> BrainBriefing:
    """Generate a brain briefing from a Brain instance.

    Includes all PATTERN+ rules by default. Each rule = 1 line in the
    output, so 48 rules = ~50 lines. The format is dense enough that
    rule count doesn't cause bloat — verbosity does.

    Args:
        brain: A gradata.brain.Brain instance.
        max_rules: Cap on rules (0 = no cap, include all qualifying).
        min_confidence: Minimum confidence to include (default 0.60 = PATTERN+).
        include_instincts: If True, also include INSTINCT-tier (low confidence).

    Returns:
        BrainBriefing with filtered, high-value context only.
    """
    briefing = BrainBriefing()

    # Extract rules from lessons
    try:
        try:
            from gradata_cloud.graduation.self_improvement import parse_lessons
        except ImportError:
            from gradata.enhancements.self_improvement import parse_lessons

        # Find lessons file
        lessons_path = None
        if hasattr(brain, "dir"):
            candidates = [
                brain.dir / "lessons.md",
                brain.dir.parent / ".claude" / "lessons.md",
            ]
            for p in candidates:
                if p.is_file():
                    lessons_path = p
                    break

        if lessons_path:
            text = lessons_path.read_text(encoding="utf-8")
            lessons = parse_lessons(text)

            # Filter: only include lessons above min_confidence
            allowed_states = {"RULE", "PATTERN"}
            if include_instincts:
                allowed_states.add("INSTINCT")

            for lesson in lessons:
                state_upper = lesson.state.value.upper()
                if state_upper in allowed_states and lesson.confidence >= min_confidence:
                    briefing.rules.append(
                        BriefingRule(
                            category=lesson.category,
                            description=lesson.description,
                            confidence=lesson.confidence,
                            state=state_upper,
                            fire_count=lesson.fire_count,
                        )
                    )

            # Sort by confidence descending, optionally cap
            briefing.rules.sort(key=lambda r: r.confidence, reverse=True)
            if max_rules > 0:
                briefing.rules = briefing.rules[:max_rules]
    except Exception:
        pass

    # Extract quality metrics
    try:
        from gradata._brain_manifest import _quality_metrics

        ctx = brain.ctx if hasattr(brain, "ctx") else None
        quality = _quality_metrics(ctx=ctx)
        briefing.brain_health = {
            k: v for k, v in quality.items() if v is not None and v != [] and v != {}
        }
    except Exception:
        pass

    # Extract recent corrections from events
    try:
        events = brain.query_events(event_type="CORRECTION", last_n_sessions=5, limit=10)
        for evt in events:
            data = evt.get("data", {})
            briefing.recent_corrections.append(
                {
                    "severity": data.get("severity", "unknown"),
                    "category": data.get("category", "UNKNOWN"),
                    "summary": data.get("summary", ""),
                }
            )
    except Exception:
        pass

    # Add anti-patterns from the negative rule library
    try:
        from gradata.enhancements.quality_monitoring import DEFAULT_ANTI_PATTERNS

        briefing.anti_patterns = list(DEFAULT_ANTI_PATTERNS)
    except ImportError:
        pass

    return briefing


def export_briefing(
    brain: Any,
    output_dir: str | Path = ".",
    formats: list[str] | None = None,
) -> dict[str, Path]:
    """Export brain briefing to one or more agent-specific files.

    Args:
        brain: A gradata.brain.Brain instance.
        output_dir: Directory to write files to.
        formats: List of target formats ("claude", "cursor", "copilot", "generic").
            Defaults to all.

    Returns:
        Dict mapping format name to the file path written.
    """
    briefing = generate_briefing(brain)
    if not briefing.has_content:
        return {}

    output_dir = Path(output_dir)
    formats = formats or list(EXPORT_TARGETS.keys())
    markdown = briefing.to_markdown()

    written: dict[str, Path] = {}
    for fmt in formats:
        target = EXPORT_TARGETS.get(fmt)
        if not target:
            continue

        filepath = output_dir / target
        filepath.parent.mkdir(parents=True, exist_ok=True)
        filepath.write_text(markdown, encoding="utf-8")
        written[fmt] = filepath

    return written


# ═══════════════════════════════════════════════════════════════════════
# Health Reports (from reports.py)
# ═══════════════════════════════════════════════════════════════════════

# Mtime-based cache for parsed lessons (avoids re-parsing on repeated health checks)
_lessons_cache: dict = {"path": None, "mtime": 0.0, "count": 0}


def _count_active_lessons(brain_dir: Path) -> int:
    """Count active lessons with mtime cache (skips re-parse if file unchanged)."""
    lessons_path = brain_dir / "lessons.md"
    if not lessons_path.is_file():
        return 0
    mtime = lessons_path.stat().st_mtime
    if _lessons_cache["path"] == str(lessons_path) and _lessons_cache["mtime"] == mtime:
        return _lessons_cache["count"]
    try:
        from gradata._core import _filter_lessons_by_state
        from gradata.enhancements.self_improvement import parse_lessons

        lessons = parse_lessons(lessons_path.read_text(encoding="utf-8"))
        count = len(_filter_lessons_by_state(lessons, min_state="INSTINCT"))
        _lessons_cache.update({"path": str(lessons_path), "mtime": mtime, "count": count})
        return count
    except Exception:
        return 0


@dataclass
class HealthReport:
    """Brain health assessment."""

    healthy: bool = True
    issues: list[str] = field(default_factory=list)
    sessions_total: int = 0
    events_total: int = 0
    lessons_active: int = 0


def generate_health_report(db_path=None, ctx=None) -> HealthReport:
    """Generate a basic health report from the brain database."""
    report = HealthReport()
    try:
        import sqlite3

        db = Path(db_path) if db_path else (Path(ctx.brain_dir) / "system.db" if ctx else None)
        if db and db.exists():
            conn = sqlite3.connect(str(db))
            report.sessions_total = (
                conn.execute("SELECT COUNT(DISTINCT session) FROM events").fetchone()[0] or 0
            )
            report.events_total = conn.execute("SELECT COUNT(*) FROM events").fetchone()[0] or 0
            conn.close()
    except Exception:
        report.issues.append("Could not read database")
        report.healthy = False

    # Count active lessons (mtime-cached to avoid re-parsing on repeated calls)
    try:
        brain_dir = Path(db_path).parent if db_path else (Path(ctx.brain_dir) if ctx else None)
        if brain_dir:
            report.lessons_active = _count_active_lessons(brain_dir)
    except Exception:
        pass  # Non-critical — lessons count is informational

    return report


def format_health_report(report: HealthReport) -> str:
    """Format health report as human-readable string."""
    status = "HEALTHY" if report.healthy else "UNHEALTHY"
    lines = [
        f"Brain Health: {status}",
        f"  Sessions: {report.sessions_total}",
        f"  Events: {report.events_total}",
        f"  Active lessons: {report.lessons_active}",
    ]
    if report.issues:
        lines.append("  Issues:")
        for issue in report.issues:
            lines.append(f"    - {issue}")
    return "\n".join(lines)


def export_session_csv(db_path=None, ctx=None) -> str:
    return ""


def generate_metrics_report(db_path=None, window: int = 20, ctx=None) -> str:
    return "Metrics report: use gradata cloud for detailed reports."


def generate_rule_audit(db_path=None, ctx=None) -> str:
    return "Rule audit: use gradata cloud for detailed audits."
